# Generated by Django 3.2.5 on 2021-08-16 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_listing_bids_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='item_category',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction_listing',
            name='item_description',
            field=models.CharField(default=django.utils.timezone.now, max_length=510),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction_listing',
            name='item_startbid',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction_listing',
            name='item_title',
            field=models.CharField(default=-1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction_listing',
            name='item_url',
            field=models.CharField(default=-1, max_length=510),
            preserve_default=False,
        ),
    ]
