# Generated by Django 3.2.5 on 2021-08-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_auction_listing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='item_url',
            field=models.CharField(max_length=512),
        ),
    ]
