# Generated by Django 3.2.5 on 2021-08-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_user_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='item_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
