# Generated by Django 3.2.5 on 2021-09-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auction_listing_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listing',
            name='user',
        ),
        migrations.AddField(
            model_name='auction_listing',
            name='user_id',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
