# Generated by Django 3.2.5 on 2021-09-04 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_auction_listing_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_listing',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_listed', to='auctions.auction_listing'),
        ),
        migrations.AlterField(
            model_name='user_listing',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
