# Generated by Django 3.2.5 on 2021-09-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20210904_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='item_id',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='item_id',
            field=models.ManyToManyField(related_name='item_watched', to='auctions.Auction_listing'),
        ),
    ]
