# Generated by Django 3.2.5 on 2021-09-05 15:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auto_20210905_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='user_id',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='user_id',
            field=models.ManyToManyField(related_name='user_watching', to=settings.AUTH_USER_MODEL),
        ),
    ]
