# Generated by Django 3.2.5 on 2021-09-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_auto_20210905_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.12, max_digits=7),
            preserve_default=False,
        ),
    ]
