# Generated by Django 3.2.5 on 2021-09-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_auto_20210905_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='item_id',
            field=models.CharField(max_length=510),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='user_id',
            field=models.CharField(max_length=510),
        ),
    ]
