# Generated by Django 3.2.5 on 2021-09-05 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_auto_20210905_1702'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
