# Generated by Django 3.2.5 on 2021-09-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0030_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='item_startbid',
            field=models.FloatField(),
        ),
    ]
